### PR TITLE
Memory consumption

### PR DESCRIPTION
**Pull request by Anber**
## Motivation

Memory management is far from optimal. Let's fix it.

### How it started

With enabled Linaria:
```
{
  rss: 2658156544,
  heapTotal: 2518843392,
  heapUsed: 1744077720,
  external: 4438696,
  arrayBuffers: 1480808
}

✓ 4846 modules transformed.

✓ built in 39.06s
```

With disabled Linaria:
```
{
  rss: 1270349824,
  heapTotal: 1151057920,
  heapUsed: 923673784,
  external: 4455888,
  arrayBuffers: 1498000
}

✓ 4349 modules transformed.

✓ built in 16.58s
```
### How it ended

```
{
  rss: 1758117888,
  heapTotal: 1624358912,
  heapUsed: 1517192880,
  external: 4878561,
  arrayBuffers: 1920673
}

✓ 4846 modules transformed.

✓ built in 34.18s
```

### CODE REVIEW

**Comment by PierreGUI** [comment]
Do you need any logs from a failing build (heap out of memory)?

**Comment by Anber** [comment]
@PierreGUI thank you, but I don't need it now. I'll finish cache optimisation tomorrow, and then we will see what to do.

**Comment by Anber** [comment]
@PierreGUI @layershifter I hope, it's ready for testing.

**Comment by PierreGUI** [comment]
Hey @Anber thanks! I tried to build and got this error: `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`
Looks different from the one before, albeit still a "out of memory" 😢

**Comment by Anber** [comment]
@PierreGUI, let's try two things:
1. Add to your Linaria config the following fragment:
```
features: {
  globalCache: false,
  happyDOM: false,
}
```

2. Run build with `DEBUG=linaria:*,-*:source*`

**Comment by PierreGUI** [comment]
Hey @Anber, 
Yes I have tried increasing `max-old-space-size` but it doesn't help.

1. Running with no `globalCache` nor `happyDOM`
It takes a very long time and spawns this error a lot (I stopped at `21% building 0/2 entries 4095/4200 dependencies 1014/1208 modules`, ~90 errors :
```
Error during transform of /src/components/clients/campaigns/NotificationBanner.view.tsx: RangeError: Maximum call stack size exceeded
    at StackOfMaps.join (/Users/pierre/code/linaria/packages/babel/lib/transform/helpers/StackOfMaps.js:70:16)
    at new Entrypoint (/Users/pierre/code/linaria/packages/babel/lib/transform/Entrypoint.js:36:19)
    ...
```

3. Running with `DEBUG` flags
It creates a file that is 1282240B (~1.3mB).

So the hypothesis of an infinite loops grows stronger 🤔

**Comment by Anber** [comment]
@PierreGUI have you tried with the last version? We have found and fixed one infinity loop yesterday.

**Comment by Anber** [comment]
I see that you tried with the old version. @layershifter had the same StackOfMaps errors but with the last version everything is ok, however for such amount of modules it may require around 8Gb heap size. I will try to figure out how to reduce memory consumption, possibly at the expense of performance.

**Comment by PierreGUI** [comment]
Ehm, I pulled this branch's HEAD, ... and then forgot to `prepare` 😮‍💨   
Ok trying again.

**Comment by Anber** [comment]
Looks like we have the new champion by the size of the codebase :) Anyway, the challenge accepted.

**Comment by PierreGUI** [comment]
I've tried this version and the build gets stuck at some point (early 10% webpack progress), then it slowly grows in memory (I've tried up to 16gB) until it reaches the limit and blows up. In the meantime no new progress is displayed.  
Let me know how I can help you finding that loop/leak and patch it!

**Comment by Anber** [comment]
@PierreGUI I'm going to add more debug info, and then we will try to figure out what happens in your project.

**Comment by PierreGUI** [comment]
Ok thanks 👍   
FYI I managed to get an out of memory crash also with `globalCache: false` when I enable multiple webpack entrypoints (max 16gB RAM).

**Comment by Anber** [comment]
Hi @PierreGUI!

Have you checked the last published version?

**Comment by PierreGUI** [comment]
Amazing work! Thanks. The build no longer crashes and seems quite fast. There are a bunch of errors now, mostly types, I'll have a look and report them if necessary

**Pull request merged**
