### PR TITLE
Chore: Upgrade src/website to use css-loader 2.x

### PR DESCRIPTION
**Pull request by hinok**
- This commit upgrade css-loader to 2.1.0 to show how webpack's configuration
should look like for new users who may install the newest version of css-loader
that has breaking change regarding css-modules

More info:
https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#breaking-changes

**Summary**

New users may install css-loader directly like 

```bash
npm install css-loader
# or
yarn add css-loader
```

and these commands will install `css-loader 2.1.0`. Since the `2.x` [css-modules are disabled by default](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#breaking-changes)

> by default css modules are disabled (now modules: false disable all css modules features), you can return old behaviour change this on modules: 'global'

This commit upgrade css-loader to the newest version - `2.1.0` and also set `modules: "global"` in `webpack.config.js` so newcomers won't struggle with the problem "why my global styles don't work".

**Test plan**

Website should look exactly the same as the production version

**Production**

zrzut ekranu 2019-02-14 o 23 38 56
zrzut ekranu 2019-02-14 o 23 39 33
zrzut ekranu 2019-02-14 o 23 39 41

**After changes**

zrzut ekranu 2019-02-14 o 23 39 59
zrzut ekranu 2019-02-14 o 23 40 12
zrzut ekranu 2019-02-14 o 23 40 04

### CODE REVIEW

**Comment by hinok** [comment]
Not sure why `ci/circleci: lint-and-typecheck` is failing

```bash
Monitor logs will go to /tmp/flow/zShomezScirclecizSlinaria.monitor_log
Lost connection to the flow server (0 retries remaining): /Out of retries, exiting!
error Command failed with exit code 7.
```

**Comment by satya164** [comment]
Thanks for the PR.

I'm a bit confused by what the change means. I thought that css modules were always disabled by default. Didn't know they allowed `global`/`local` in plain CSS.

How does this change affect configuration with Linaria? From the css-loader docs, I see:

> Disable the CSS Modules spec, all CSS Modules features (like `@value`, `:local`, `:global` and `composes`) will not work

Linaria doesn't use any of these features, so this shouldn't matter, no?

Don't worry about Flow. Doesn't seem related to this PR, just general flakyness.

**Comment by hinok** [comment]
Currently `css-loader` is locked on `1.0.0` where `:global` just works.

The problem appears when you install `css-loader` (like I did...) directly and you end with `css-loader 2.1.0`. In `src/website` there is an example how global CSS can be used but it doesn't work anymore with the new `css-loader`.

Code like this:

```css
:global {
  body { color: red };
}
```

should generate CSS as:

```css
body { color: red };
```

Unfortunately with `css-loader 2.x` css-modules are disabled and final CSS looks like that:

```css
:global body { color: red }; /* :( .... */
```

This commit just upgrade `css-loader` and `webpack.config.js` so everything works again with the newest version.

You can easily see that if you upgrade `css-loader` to `2.1.0`, global styles are broken

zrzut ekranu 2019-02-15 o 00 17 30

zrzut ekranu 2019-02-15 o 00 17 49

zrzut ekranu 2019-02-15 o 00 19 00

**Comment by satya164** [comment]
Oops. For some reason I thought it was handled by `stylis` and not `css-loader`.

Can you change `:global` to `:global()`? That way `stylis` should handle it regardless of `css-loader` config. We also need to update https://github.com/callstack/linaria/blob/master/docs/BASICS.md#adding-global-styles

**Comment by hinok** [comment]
Sorry for the confusion, I thought that it's `css-loader` responsibility to handle global styles. I'm not familiar with `stylis`.

PR updated.

**Comment by satya164** [comment]
@all-contributors let's add hinok for docs

**Pull request merged**
