### PR TITLE
feat: add Rollup plugin

### PR DESCRIPTION
**Pull request by johanholmerin**
Added Rollup plugin and updated docs.

### CODE REVIEW

**Comment by satya164** [comment]
Thanks a lot for the PR! What do you think about being added to the collaborators?

**Comment by johanholmerin** [comment]
Yes, I would be interested in that. Could we chat about the project somewhere?

**Comment by satya164** [comment]
@johanholmerin you can join our discord channel. link in README

**Comment by johanholmerin** [comment]
I have added Flow types

**Pull request merged**
