### PR TITLE
Minimal IE Runtime

### PR DESCRIPTION
**Pull request by nhooyr**
See #445

**Summary**

Adds a very minimal runtime for IE. Not the most robust but should work well for our purposes.

See #445

**Test plan**

Not really sure yet.

### CODE REVIEW

**Comment by nhooyr** [comment]
The way it work is that when a css variable needs to be modified, instead of just adding an inline style, the IE code will find the rule in the stylesheet that uses the css variable on the class, replace the variable with the value and add this new rule to a dynamically injected stylesheet.

**Comment by nhooyr** [comment]
Not sure if the rule cache here is necessary. For the rule on every dynamic CSS variable, is the selector just the class?

**Comment by pbitkowski** [comment]
Thanks for your contribution! Is this possible to extract this logic to another library, to make this opt-in feature? I know it's tiny, but we don't to do it by default to keep our core small and happy.

**Comment by dreyks** [comment]
@pbitkowski how do you feel about making it a separate library indeed but scope it under callstack? that way the core could still be kept small but the library won't get lost in the future?

**Comment by nhooyr** [comment]
Don't have the time to work on this anymore. Someone else feel free to continue.

**Pull request closed without merging**
