### PR TITLE
tests: fix website integration tests

### PR DESCRIPTION
**Pull request by satya164**
not sure why they broke, but probably because of updates to the fonts

### CODE REVIEW

**Comment by thymikee** [comment]
Screenshot diff suggests that the font is no longer Montserrat, while it should be (maybe puppeteer doesn't wait for google font to download).

**Comment by satya164** [comment]
> Screenshot diff suggests that the font is no longer Montserrat

Looks like Montserrat to me, but thinner

**Comment by thymikee** [comment]
But we use the bold one for hero... https://github.com/callstack/linaria/blob/0fde9fd79c185a3451a93c64b8a0e925afc141a5/website/src/components/Hero.js#L35.

**Comment by satya164** [comment]
> But we use the bold one for hero

All of them look thinner in the new snapshot, both body and header ones.

**Comment by thymikee** [comment]
Do they look like this locally? If so, I'm fine merging it.

**Comment by satya164** [comment]
Yea

**Pull request merged**
