### PR TITLE
chore: link to coverage report of the branch in pr comment

### PR DESCRIPTION
**Pull request by satya164**

### CODE REVIEW

**Comment by thymikee** [comment]
@satya164 is it possible to change the message to:

Hey, thank you for your pull request 🤗. 
The coverage report for this branch can be viewed [here](https://1401-92112844-gh.circle-artifacts.com/0/coverage/lcov-report/index.html).

**Comment by zamotany** [comment]
What's the motivation behind this?

**Comment by satya164** [comment]
@zamotany to reply with a friendly thank you message to contributors and to post the link to the coverage report so that we can remove codecov (which you wanted to do).

**Comment by zamotany** [comment]
👍 but what about coverage badge?

**Comment by satya164** [comment]
@zamotany we can keep the integration and only disable the comment.

**Pull request merged**
