### PR TITLE
feats: modifiers and class name optimizations

### PR DESCRIPTION
**Pull request by brandonkal**
**Summary**

This PR adds the following:
- Improves babel to support arrow functions. This means shorter interpolations inside our styles.
- Adds [modifier class](https://github.com/callstack/linaria/issues/234) support. This is what excites me. See my [RFC](https://github.com/callstack/linaria/issues/427) for context and my earlier thought process. Display logic that is a function of props can be used with normal Javascript, though the syntax looks close to CSS attribute selectors.
- Prefix and suffix support
- Generated BEM-like modifiers. No need to name all those modifiers! JS logic is turned into a CSS modifier name, all of this is stripped away after development:
- Tiny class names

This is a step towards my [RFC on unifying the styled and css APIs](https://github.com/callstack/linaria/issues/427). With the modified Linaria, I have converted some of my own UI components from composition with css to modifiers. The result was slightly less code and components that control their own styles.

**Test plan**

I have added Jest tests for new features.

**Note:** I submitted this for feedback. Although I wish for these features to merged soon, there are still some things I will need input on. I haven't received any input on my RFC yet, so I am hoping a PR that implements some of those ideas may be more effective.
This is the feedback I am looking for:
1. How caching would work with the tiny class names feature. Perhaps a seperate cache should be maintained? This may be a non issue as switching from showing displayName at the start of a classname also throws out linaria's cache.
2. Implementation approach for tiny class names feature: Right now, it is performing regex replacents on result.code and result.cssText after calling transform. Because the transform is syncronous, another approach would be to pass the renaming function as an argument of transform().
3. How to add a method to not minimize a classname/variable. It may be desirable to not minimize some classes/variables names in production.

Known Todos:

- [x] The code assumes `props.key` when validating a modifier class. The example below is valid if state is replaced with props. 
```jsx
const Button = state => styled.button`
  &.${[state.primary]} { color: blue }
`
```
- [x] ~~Accept a configurable array of classnames/variables that should not be minifized~~. This is not possible as classnames are generated in the babel transform. So there really isn't a need for this.
- [x] Only shorten class names in production
- [x] Configure suffix and prefix to work after tiny class name step. This way libraries can have classes with short names like `mui_a`

Unrelated areas for improvement found while working on the code:
The __linaria objects for babel interpolation are not used by styled at runtime. They should be removed from production output.

An example modifier class:
```jsx
export default function Index() {
  return (
    <Page primary>
      <Header />
      <Hero />
    </Page>
  );
}

const Page = props => styled.div`
  background: linear-gradient(to bottom right, #b24592, #f15f79);
  color: #fff;
  min-height: 100vh;
  text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.08);
  &.${[props.primary]} {
    color: #b2ffe6;
  }
`;
```

### CODE REVIEW

**Comment by brandonkal** [comment]
This is ready for review. I now consider these features implemented and complete! Thanks.

**Comment by pbitkowski** [comment]
Hi, we're happy that you send your PR, but you have implemented the RFC but we haven't had chance to read and comment it. Let's discuss it further on the RFC issue and then decide what to do about it.

**Comment by brandonkal** [comment]
Yes, let's do that! Thanks.

**Comment by brandonkal** [comment]
Note for those who care: New changes/fixes are being pushed to a seperate branch and are published [@brandonkal/linaria](https://www.npmjs.com/package/@brandonkal/linaria).

Here is a summary of the improvements.

1. Much smaller styled runtime! No dependency on @emotion/is-prop-valid.
2. Simple and predictable prop filtering. Props that end in "$" are not forwarded to the DOM.
3. Modifiers! All style logic can be contained inside your CSS.
4. Improved babel support for arrow functions. This means shorter interpolations inside our styles.
5. Generated BEM-like modifiers. No need to name all those modifiers! Javascript logic is transformed into a CSS modifier name, all of this is stripped away after development:
6. Tiny class names in production with optional prefix and suffix support
7. Uses postCSS rather than stylis. This allows for a much deeper integration with your existing CSS pipeline.
8. High resolution source maps. Even nested selectors and modifiers point to the proper line rather than the start of the template literal.
9. Vastly improved Typescript types and support.

I understand people are busy, but I just wanted to point out that there are other useful improvements in here (e.g. Typescript fixes) that could be merged.

I know this is a big PR, so perhaps the list above is helpful for review. I would be happy to break this PR into several smaller ones. But it has been 53 days since trying to start a discussion here. I see that there is some recent activity on this repo, so I just wanted to post this note to ensure this is not forgotten and work is not duplicated.

**Comment by brandonkal** [comment]
Requesting a response.

**Pull request closed without merging**
