### PR TITLE
support TypeScript expressions

### PR DESCRIPTION
**Pull request by Anber**
**Summary**

This PR implements support of TS-specific expressions such as `enum`, `… as …`, etc.  

**Test plan**

New tests were added.

### CODE REVIEW

**Comment by Anber** [comment]
I've probably finished with basic support of TS. In this PR I've also made some steps to extract language-specific features into the separate pluggable modules, but it will be better if I finish this work within the issue #413

**Comment by Alivejke** [comment]
Is it going to be merged some time soon? It seems like a ready solution to a problem that we experience and we would really appreciate if it can be released :)

**Comment by Anber** [comment]
@Alivejke may I ask you to describe your problem?
I hope we will be ready for the next canary release by the end of this weekend and you can help us by providing some edge cases for tests :)

**Comment by Rawphs** [comment]
Hi @Anber, I work with @Alivejke and he asked me to provide an example so here it goes:

```
enum Colors {
  BLUE = '#27509A'
}

const Title = styled.h1`
  color: ${Colors.BLUE};
`;

export const Yell = () => (
  <Title>AAAAAAAAAAA</Title>
);
```

That's the smallest example I could come up with, we're getting the following error when running storybook:

```
ERROR in <file-name>
Module build failed (from ./node_modules/linaria/loader.js):
SyntaxError: <file-name>: An error occurred when evaluating the expression: Colors is not defined. Make sure you are not using a browser or Node specific API.
```

Does that help? :D

**Comment by Anber** [comment]
@Rawphs it definitely does :) At least it showed that the latest version doesn't process `enum` for some reasons. Do you use `@babel/preset-typescript `? It looks like it [does not understand `enum` at all](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYOwrgtgBAwg9gGzgJwM5QN4CgpQEIAyAqgKJQC8UA5AMQBMA7AKwAMAnAIJVYC-WWAYzghUAFygAVAJaiEwClDEBPOQBMAdAAsAjAAMcUIUmQAuKABIM8Y6nWFSPANxZdzrMAAeABxTihI8QBNYAQEBQAKAEoKAD4ocIMAHmlZYBiODMysjkSAehS5GKxIxyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3%2Ces2015-loose%2Ctypescript&prettier=false&targets=&version=7.6.4&externalPlugins=)

**Comment by Rawphs** [comment]
@Anber I am using `@babel/preset-typescript`. We're first writing the components with Storybook stories, and the webpack config for storybook uses `babel-loader` before `linaria/loader`. I can share the config if you'd like

Enums are only causing an error within linaria, _unless_ they're inside a function. The example below works just fine.

```
const Title = styled.h1`
  color: ${(props) => Colors[props.color]};
`;
```

**Comment by Anber** [comment]
Hi @Rawphs,

Your case will be fixed after merging PR #498. This PR is outdated.

Thank you for the feedback!

**Comment by kallebornemark** [comment]
Will the be reopened now once #498 is merged?

**Comment by Anber** [comment]
@kallebornemark TS should work in the 1.4-beta. Have you experienced problems with it?

**Pull request closed without merging**
