### PR TITLE
feat: scope option for libraries

### PR DESCRIPTION
**Pull request by chrisbateman**
**Summary**

see #299, #208, #178 and updates to docs/CONFIGURATION.md.

I wasn't sure what kind of API you had in mind for this feature, so I won't be offended if you want to go in a different direction!

**Test plan**

Added some Jest tests, linked locally and tested scope: false/true/"custom" and verified that different class names were generated for each.

### CODE REVIEW

**Comment by chrisbateman** [comment]
Gotcha – that'd work for me! I could make that update later today – any suggestions for the config name? `prefix`? `classPrefix`?

**Comment by chrisbateman** [comment]
@satya164 Let me know if this is more like what you were thinking of!

**Comment by thymikee** [comment]
Just a heads-up: we're working on TS migration in #398 and will let you know once we're done. Would you be so kind and bear with us until it's ready and rebase then?

**Comment by pbitkowski** [comment]
@satya164 can we merge it after TS migration? Could you take a look?

**Comment by chrisbateman** [comment]
@thymikee can do - thanks for the update!

**Comment by chrisbateman** [comment]
@thymikee @satya164 Would there be any value in pointing this PR at the `develop` branch? Or are y'all plannin to merge that to master at some point?

**Comment by jayu** [comment]
Hi, @chrisbateman Do you have the capacity and will to refactor this to the point it would be possible to merge it to current `develop`?

**Comment by amaranth** [comment]
How is this different from setting the existing `classNameSlug` setting to `"MyScope_[hash]"`?

**Comment by jayu** [comment]
Lol I didn't notice that :o Looks like `classNameSlug` PR was introduced after this one was opened. So this PR does not make sense anymore since we have the possibility to add a prefix to the class name. Thanks for that finding @amaranth

**Pull request closed without merging**
