### PR TITLE
chore: add MIT license

### PR DESCRIPTION
**Pull request by thymikee**
**Summary**

Hey, we're missing the license! We should also add a comment with copyright, like we do in Haul

### CODE REVIEW

**Comment by satya164** [comment]
> We should also add a comment with copyright

Why do we need a comment?

**Comment by thymikee** [comment]
So that it's preserved when somebody is copying our code (at least when doing so legally).

**Comment by thymikee** [comment]
cc @grabbou – should we add license headers to src files?

**Comment by grabbou** [comment]
I think we can add it. I got used to doc blocks at the top and that just reads nicer to me

**Pull request merged**
